### PR TITLE
scripts: Fixes deprecated use of `--with-relaxed`

### PR DESCRIPTION
**Pull request by n-riesco**
@willingc I haven't tested it, but I reckon it fixes your compilation problem.

From https://github.com/nteract/nteract/issues/1189#issuecomment-260534970

See https://github.com/zeromq/libzmq/commit/7129187f877317fe6af8a5ece3638782ceb0d602

### CODE REVIEW

**Comment by n-riesco** [comment]
AppVeyor got a 404. Is it possible to trigger the test again?

**Comment by lgeiger** [comment]
I don't think this will fix the compilation problem :(

We switched back to libzmq 4.1.6 for linux because of #94 so this will fix the warning on OS X but won't work on linux:
`configure: WARNING: unrecognized options: --disable-pedantic`

**Comment by willingc** [comment]
@n-riesco @lgeiger Thanks for trying to track this down. Will work on later and see if I can figure out the Sierra issue on OS X.

**Comment by n-riesco** [comment]
Would something like this be OK?
```sh
if [ "$ZMQ" = "4.1.6" ]; then
	/configure --prefix=$ZMQ_PREFIX --with-relaxed --enable-static --disable-shared ;
else
	./configure --prefix=$ZMQ_PREFIX --disable-pedantic --enable-static --disable-shared ;
fi
```

**Comment by lgeiger** [comment]
@n-riesco That would be perfect 👍

**Comment by n-riesco** [comment]
@lgeiger Shall I wait for #99?

**Comment by lgeiger** [comment]
Go ahead. I can rebase #99 after this is merged.

**Comment by rgbkrk** [comment]
Oh whoops, I just noticed you wanted to rebase in the opposite order.

**Comment by rgbkrk** [comment]
Can you rebase this @n-riesco and we'll merge right away.

**Comment by n-riesco** [comment]
Moved to  PR #100

**Pull request closed without merging**
