### PR TITLE
Upgrade ZMQ to 4.3.1

### PR DESCRIPTION
**Pull request by rgbkrk**
Not sure if this is everything that has to be done for an upgrade. For now, I'll just kick this PR off to see how CI performs.

### CODE REVIEW

**Comment by reqshark** [comment]
looks like appveyor's windows doesnt like that dll?  @rgbkrk did you compile the dll?

**Comment by reqshark** [comment]
ahh nvm checking these out right now https://github.com/zeromq/zeromq.js/tree/master/scripts

**Comment by rolftimmermans** [comment]
6.0 has libzmq 4.3.2 now, so users looking for the latest version should probably use that. There are no published Windows builds for 4.3.x AFAIK so supporting this in 5.x is a bit more tricky...?

**Comment by rgbkrk** [comment]
I'll just close this.

**Pull request closed without merging**
