### PR TITLE
Socket::Socket: Don't throw a C++ exception

### PR DESCRIPTION
**Pull request by n-riesco**
Fixes https://github.com/nteract/hydrogen/issues/515

(needs testing since I can't reproduce the issue in Hydrogen)

### CODE REVIEW

**Comment by minrk** [comment]
👍 to the principle. There are several other `throw std::runtime_error(ErrorMessage());` in `binding.cc`, presumably they should all get the same update?

**Comment by n-riesco** [comment]
@minrk I think so, since I don't see any `try-catch` blocks in `binding.cc`.

I don't mind making another PR for the remaining 9 cases, if this PR fixes https://github.com/nteract/hydrogen/issues/515 .

**Comment by minrk** [comment]
The issue seems like it should be pretty hard to reproduce if this line is the culprit. It would mean successfully creating a socket, but failing to retrieve its FD. The only logical explanation I have for that is libzmq < 3 is in use (FD was not an option before then, so EINVAL would be raised), but I don't think that's possible with zeromq.js, is it?

**Comment by lgeiger** [comment]
👍 for handling C++ exceptions with NAN.

Based on the logs from https://github.com/nteract/hydrogen/issues/515 it's the same issue as https://github.com/zeromq/libzmq/issues/2175 and https://github.com/electron/electron/issues/8068. So @rgbkrk may be able to test this.

**Comment by n-riesco** [comment]
@minrk Another possibility is that the socket is thread safe (e.g. ZMQ_CLIENT). See [here](https://github.com/zeromq/libzmq/blob/b031325996597759dce1130c63449422dacf8f9e/src/socket_base.cpp#L392-L396).

**Comment by minrk** [comment]
Good catch, though Hydrogen should't be creating any of the new threadsafe sockets, because there aren't used anywhere in Jupyter protocols.

**Comment by rgbkrk** [comment]
Based on what I looked into yesterday, this helps Atom (and Electron) not crash yet doesn't handle the core problem: https://github.com/zeromq/libzmq/issues/2175

**Comment by rgbkrk** [comment]
https://github.com/zeromq/libzmq/pull/2176 did make it into the 4.2.0 release it looks like, yet doesn't seem to fix it for users who control their build environment on Atom. 
¯\\\_(ツ)\_/¯

**Comment by n-riesco** [comment]
@rgbkrk Oh! So the problem is that OSX 10.12 now provides `clock_gettime`, and the binaries distributed by `zeromq.js` are built in OSX 10.12, and fail when run on OSX 10.11.

The OSX binaries distributed by `zeromq.js` are built by Travis, isn't it? Would `osx_image: xcode7.2` work around this problem?

**Comment by rgbkrk** [comment]
Yup, it all centers around `clock_gettime`. I incorrectly assumed earlier that it was an issue with the changes to the implementation of `poll`.

On Atom it should be rebuilding for the user with their local build environment, which is exactly the circumstance mentioned in the issue body here https://github.com/zeromq/libzmq/issues/2175 - a conflict between what's available at build time and run time.

For the time being we should probably lower the xcode version like you suggest (assuming we can build that).

**Comment by lgeiger** [comment]
[Travis defaults to XCode 7.3](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version) so we should be good for the prebuilts.

**Comment by rgbkrk** [comment]
Ah, that's why zeromq tests across both Mac versions worked just fine.

**Pull request merged**
