### PR TITLE
test: Run mocha tests with Electron

### PR DESCRIPTION
**Pull request by Bartel-C8**
Resolves https://github.com/zeromq/zeromq.js/issues/534

### CODE REVIEW

**Comment by Bartel-C8** [comment]
Depends on https://github.com/zeromq/zeromq.js/pull/546

**Comment by Bartel-C8** [comment]
Resolved merge conflict + fixed mocha test not exiting in CI

**Comment by Bartel-C8** [comment]
Reased again.

**Review by aminya — APPROVED** [review]
Thanks for the changes

**Pull request merged**
