### PR TITLE
chore(package): update prebuild to version 7.1.0

### PR DESCRIPTION
**Pull request by lgeiger**
prebuild 7.0.0 removed support for node 0.10 and 0.12.
Closes #210

### CODE REVIEW

**Comment by rgbkrk** [comment]
What kind of release should the next one be? Is this a major change for us?

**Comment by rgbkrk** [comment]
(Note: I'm of course a fan of dropping pre-LTS releases)

**Comment by lgeiger** [comment]
Since it's only a dev dependencies we don't have to make it a major one. We stopped shipping prebuilts for 0.10 and 0.12 a while ago anyway.

**Comment by rgbkrk** [comment]
I re-kicked the build and now the PR build passes. Not the push though.

**Pull request closed without merging**
