### PR TITLE
scripts: fix build against node-x86

### LINKED ISSUE #214: Failure to build against node-x86 on a x64 OS
The initial issue was reported in https://github.com/nodejs/citgm/pull/527

I'm using this `Dockerfile` to reproduce the issue:
```Dockerfile
FROM node:8.9.3

# Add i386 architecture
RUN dpkg --add-architecture i386 \
  && apt-get update \
  && apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386

RUN apt-get install -y gcc-multilib g++-multilib

RUN apt-get install -y vim

USER node
WORKDIR /home/node

# Install 32bit node binary
RUN curl https://nodejs.org/dist/v8.9.3/node-v8.9.3-linux-x86.tar.gz | tar zxf -

RUN git clone https://github.com/n-riesco/zeromq.js.git

WORKDIR /home/node/zeromq.js
ENV PATH="/home/node/node-v8.9.3-linux-x86/bin:$PATH"
CMD echo $PATH \
  && node -p "process.arch" \
  && npm install
```

I have a fix for this issue and now I'm preparing a PR.

### PR DESCRIPTION
**Pull request by n-riesco**
* Added flag `-m32` when arch is `ia32`.

Fixes #214

### CODE REVIEW

**Comment by rgbkrk** [comment]
Thanks Nico. I’m a little curious about if this should instead be in the node gyp config.

At any rate we can make a patch release with this.

**Comment by n-riesco** [comment]
@rgbkrk The problem wasn't in the compilation of the node binding (the node binding is correctly built as an `ELFCLASS32`), but in the compilation of `libzmq.a`. In a 64bit OS, `libzmq.a` is built as an `ELFCLASS64` unless I use the flag `-m32`.

**Comment by rgbkrk** [comment]
Ahhhh, thanks

**Comment by lgeiger** [comment]
Cool, thanks for fixing that.

**Pull request merged**
