### PR TITLE
Fix compatibility with older Node versions

### PR DESCRIPTION
**Pull request by n-riesco**
* Use ES5 in `scripts/dowload.js`

### CODE REVIEW

**Comment by lgeiger** [comment]
Thanks!

`apm install` worked for me before as well.
Do we need to make a patch release?

**Comment by n-riesco** [comment]
I reckon so, since it makes `zeromq` uninstallable on older Node versions.

What node version is using the latest Atom?

**Comment by lgeiger** [comment]
Atom 1.12 uses node 4.4.5

I'll make a patch release to make sure it works on older versions as well.

**Comment by n-riesco** [comment]
I guess that explains why nobody came across this issue before.

**Comment by willingc** [comment]
@lgeiger You are doing good work! Thanks. :cake:

**Comment by lgeiger** [comment]
@willingc Thanks! 😃

**Pull request merged**
