### PR TITLE
Merge ZeroMQ-NG back into ZeroMQ.js

### PR DESCRIPTION
**Pull request by rolftimmermans**
This is a continuation of #189.

This is the status of my rewrite, ZeroMQ-NG, which I'd like to get merged back into ZeroMQ.js:

- [X] Rewrite from the ground up with modern JavaScript, TypeScript, Node.js & ZeroMQ semantics in mind, exposing an API for `async`/`await` and async iterators, and using the binary stable N-API to integrate with Node.js.
- [X] Recreate an API that addresses fundamental issues with ZeroMQ.js as previously outlined in #189.
- [X] Automate testing, building of prebuilt binaries which are included in the NPM package for all platforms currently supported by ZeroMQ.js. Targets Node 10+ and Electron 3+.
- [X] Implement a compatibility layer for existing versions 4.x and 5.x of ZeroMQ.js aimed at existing users.
- [X] Document the new public API surface, for use by IDEs such as VSCode and for consumption with TypeDoc (see: https://rolftimmermans.github.io/zeromq-ng/).
- [X] Implement DRAFT sockets which can be enabled with a compile time flag.
- [X] Tested in production.

Based on https://github.com/zeromq/zeromq.js/issues/189#issuecomment-426066308, the following needs to be done.

Edit: I have added a more complete list in https://github.com/zeromq/zeromq.js/issues/347, so that we can also track activities after the PR.

Regarding the version tags mentioned above, this PR tags the next version as 6.0.0-beta.1.

I'd like to invite everyone to browse, review, test and comment! You can browse the code in this pull request at `https://github.com/rolftimmermans/zeromq.js/tree/upstream`. If you wish to use the prebuilt binaries, it is available from NPM as `zeromq-ng@5.0.0-beta.26`.

### CODE REVIEW

**Comment by rolftimmermans** [comment]
Just to be clear on this: the AppVeyor check is failing because there is no need for AppVeyor anymore. Travis will also test & build from source on Windows x64 & x86.

**Comment by rgbkrk** [comment]
Ok great, we can just turn AppVeyor off for now.

**Comment by rolftimmermans** [comment]
@lgeiger @rgbkrk Perfect!

Before we move forward and merge this PR, I have two questions:

1) Are there any other maintainers we should request review/approval from before merging?

2) To automatically build & deploy new prebuilt binaries for tags pushed to the repository we need to add an encrypted API key for Github & NPM. I have created the `zeromqjs-integration` user on Github & NPM for both purposes (instead of a personal account, to avoid access to any additional repos/packages). I don't have permissions to add it to the Github repo (with commit access in order to publish documentation to `gh-pages`) or to the NPM package, however. Do you agree with this approach, and if so could any of you take care of adding the integration users? I will set up the deployment keys once that is done.

**Comment by rolftimmermans** [comment]
I have made a [separate issue](https://github.com/zeromq/zeromq.js/issues/347) to track all activities (and added a few new ones, especially for after this PR lands). Right now I'm blocked by my two questions in [my previous comment](https://github.com/zeromq/zeromq.js/pull/343#issuecomment-544469362); would be great to get some feedback!

**Comment by rgbkrk** [comment]
> Are there any other maintainers we should request review/approval from before merging?

@reqshark @ronkorving @kkoopa might have some thoughts. I don't know what their bandwidth is these days.

I'm leaning towards helping you take on more of the reins @rolftimmermans and driving this forward. It works well and is the direction we need to take for future node versions.

**Comment by kkoopa** [comment]
I think this is great.

**Comment by ronkorving** [comment]
Agreed, this is awesome! :)

**Comment by rolftimmermans** [comment]
> I'm leaning towards helping you take on more of the reins @rolftimmermans and driving this forward. It works well and is the direction we need to take for future node versions.

I would love to push this forward further, with input from everyone that is able to provide it. In the short term I'm mostly blocked by not being able to add [the integration users](https://github.com/zeromq/zeromq.js/pull/343#issuecomment-544469362) in Github & NPM to automatically build & release a beta to get some feedback from users.

**Comment by rgbkrk** [comment]
> To automatically build & deploy new prebuilt binaries for tags pushed to the repository we need to add an encrypted API key for Github & NPM. I have created the zeromqjs-integration user on Github & NPM for both purposes (instead of a personal account, to avoid access to any additional repos/packages). I don't have permissions to add it to the Github repo (with commit access in order to publish documentation to gh-pages) or to the NPM package, however. Do you agree with this approach, and if so could any of you take care of adding the integration users? I will set up the deployment keys once that is done.

@bluca or @somdoron -- do you know how to [facilitate the above request](https://github.com/zeromq/zeromq.js/pull/343#issuecomment-544469362)?

**Comment by bluca** [comment]
If you need me to set a key, send it encrypted with gpg to bluca@debian.org and I'll set it

**Comment by rolftimmermans** [comment]
> I can give the new user a write permission on the repo if needed

That would be excellent. If `zeromqjs-integration` has write access I can integrate the build process of the binaries and documentation with Travis & Github. (Security-wise it would be equivalent with write access for me, but this account is single-purpose, and if preferred I can share or transfer the credentials with/to someone else.)

**Comment by lgeiger** [comment]
@rolftimmermans Sorry for the delay. I added the integration user to the GitHub zeromq.js team and to the `npm` package. Please let me know if this is enough.

If Travis is tricky to get setup with the correct secrets, we can also try [GitHub actions](https://github.com/features/actions) which is a bit easier when it comes to secrets.

**Comment by rolftimmermans** [comment]
@lgeiger Perfect! I have added the encrypted keys and will wait for Travis to pass before merging.

**Comment by lgeiger** [comment]
Cool 👍
I properly configured Appveyor to only build branches that have an `appveyor.yml`, so we can ignore the failing build here.

**Comment by rgbkrk** [comment]
Wahoo!!!

**Comment by somdoron** [comment]
@lgeiger @rolftimmermans did you release a version to npm? I want to use the new async API

**Comment by rolftimmermans** [comment]
> @lgeiger @rolftimmermans did you release a version to npm? I want to use the new async API

Yep! Try `npm i --save zeromq@6.0.0-beta.4` or `yarn add zeromq@6.0.0-beta.4`

**Comment by somdoron** [comment]
thanks!

**Pull request merged**
