### PR TITLE
Added support for Node 13

### PR DESCRIPTION
**Pull request by giovannicalo**
As mentioned in #346, this library fails to install with Node 13.0.1, due to compilation errors.
After a quick investigation, the issue seems to be
```c++
v8::Local<v8::Value> v8::Object::Get(uint32_t index)
``` 
which [has already been deprecated for a while](https://v8docs.nodesource.com/node-12.0/db/d85/classv8_1_1_object.html#af8c3c8fa1256e7ea440616e82b461d31) and seems to have been removed in favour of
```c++
v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context> context, uint32_t index)
```
in Node 13 / V8 7.8.

This seems to fix the issue.

It's only been tested with Node 12.13.0 and 13.0.1, on Windows.

This might break compatibility with older versions of Node, however [the new method was already present](https://v8docs.nodesource.com/node-6.17/db/d85/classv8_1_1_object.html#a5552867a276e2bda013de11e8ba41e4f) ([and the old one was already deprecated](https://v8docs.nodesource.com/node-6.17/db/d85/classv8_1_1_object.html#af8c3c8fa1256e7ea440616e82b461d31)) in Node 6 / V8 5.1, so it shouldn't be the case.

It might not be the best way to fix it, but works for me.

### CODE REVIEW

**Comment by rolftimmermans** [comment]
There is also the [Nan::Get()](https://github.com/nodejs/nan/blob/master/doc/maybe_types.md#api_nan_get) helper which might be a safe alternative?

**Comment by giovannicalo** [comment]
As I said, there might be better ways to fix it.

I just needed it to work and figured I'd have a look, rather than downgrading Node, so I went with the least possible changes and stopped as soon as it worked.

Otherwise, lately I've been using [node-addon-api](https://github.com/nodejs/node-addon-api) rather than N-API, NAN or V8.

Anyway, I guess it's between
```c++
Local<Object> buf = batch->Get(Nan::GetCurrentContext(), i).ToLocalChecked().As<Object>();
```
and
```c++
Local<Object> buf = Nan::Get(batch, i).ToLocalChecked().As<Object>();
```
which is shorter and probably more stable, so might indeed be better.

**Comment by lgeiger** [comment]
@rolftimmermans What do you think, can we merge this, or should we use ` Nan::Get()`?

I am not very familiar with this, but I can do a patch release once this PR is merged.

**Comment by rolftimmermans** [comment]
Let’s just merge for now, we can always improve later!

**Comment by lgeiger** [comment]
> Let’s just merge for now, we can always improve later!

:+1: @giovannicalo Thanks for the PR. Let's ship it

**Pull request merged**
